#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  publish-nginx-docker-image:
    runs-on: nginx-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the nginx Docker image
        run: |
          docker build . --tag ghcr.io/ed2120/hello-docker-gcr-demo:latest
          docker run ghcr.io/ed2120/hello-docker-gcr-demo:latest
          docker push ghcr.io/ed2120/hello-docker-gcr-demo:latest
          